// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ap01.Models;

public partial class Customer
{
    public string CustId { get; set; }

    public string CustName { get; set; }

    public string Addr { get; set; }

    public string Phone { get; set; }
}